// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycymknzmaijxksqqcitu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeW1rbnptYWlqeGtzcXFjaXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDk5MzgsImV4cCI6MjA2OTQ4NTkzOH0.dYVCcbsAdm9A_imhoEOgq8zGHMvZWaSePJLYAaIF6Oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});